{% set name = "mhkit" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mhkit-{{ version }}.tar.gz
  sha256: 15ce26b3132fa3376975b5f05a3747ebeff54043ba713695bff14c4662781fd3

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pandas >=1.0.0
    - numpy >=1.21.0
    - scipy
    - matplotlib-base
    - requests
    - pecos >=0.3.0
    - fatpack
    - lxml
    - scikit-learn
    - nrel-rex >=0.2.63
    - six >=1.13.0
    - h5py >=3.6.0
    - h5pyd >=0.7.0
    - netcdf4
    - xarray
    - statsmodels
    - pytz
    - bottleneck
    - beautifulsoup4

test:
  imports:
    - mhkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MHKiT-Software/mhkit-python
  summary: Marine and Hydrokinetic Toolkit
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ssolson
