{% set name = "mhkit" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mhkit-{{ version }}.tar.gz
  sha256: 546dd6928d37bd16a37a04af91417a5e09d720f5a3d585dea62499a607e4c700

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2
  # https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors
  skip: True  # [py<310 or py>313]

requirements:
  # Necessary for osx_arm64 cross compilation
  # https://conda-forge.org/blog/2020/10/29/macos-arm64/
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy >=2.0.0
    - pandas >=2.2.2
    - scipy >=1.14.0
    - xarray >=2024.6.0
    - matplotlib-base >=3.9.1
    - scikit-learn >=1.5.1
    - h5py >=3.11.0
    - h5pyd >=0.18.0
    - netcdf4 >=1.7.1.post1
    - statsmodels >=0.14.2
    - requests
    - pecos >=0.3.0
    - fatpack
    - nrel-rex >=0.2.63
    - pytz
    - beautifulsoup4
    - numexpr >=2.10.0
    - lxml
    - bottleneck

test:
  imports:
    - mhkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MHKiT-Software/mhkit-python
  summary: Marine and Hydrokinetic Toolkit
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ssolson
