{% set name = "mhkit" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mhkit-{{ version }}.tar.gz
  sha256: bb36f5a3d3706085c006ee4c6dfea870614493ae063e01e557a0e5811391a4c8

build:
  script: {{ PYTHON }} -m pip install .[all] -vv --no-deps --no-build-isolation
  number: 1

requirements:
  # Necessary for osx_arm64 cross compilation
  # https://conda-forge.org/blog/2020/10/29/macos-arm64/
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - pip
    - numpy >=2.0.0
    - pandas >=2.2.2
    - scipy >=1.14.0
    - xarray >=2024.6.0
    - scikit-learn >=1.5.1
    - h5py >=3.11.0
    - h5pyd >=0.18.0
    - netCDF4 >=1.6.5
    - hdf5 >=1.14.3,<1.14.5.0a0
    - statsmodels >=0.14.2
    - requests
    - beautifulsoup4
    - numexpr >=2.10.0
    - lxml
    - bottleneck
    - pecos >=0.3.0
    - notebook
    # Recipes should usually depend on matplotlib-base as opposed to matplotlib so that runtime environments do not require large packages like qt
    - matplotlib-base >=3.9.1
    - fatpack
    - nrel-rex
    - cartopy
    - pytz

test:
  imports:
    - mhkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MHKiT-Software/mhkit-python
  summary: Marine and Hydrokinetic Toolkit
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - akeeste
    - simmsa
